name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install buildozer
        pip install requests
    - name: Build APK
      run: |
        buildozer init
        sed -i 's/^requirements =.*/requirements = python3,requests/' buildozer.spec
        buildozer android debug deploy run
